backend:
  name: github
  branch: dev
  repo: deepettas/dpettas

media_folder: "src/assets/images"
public_folder: "static/assets/images"

collections:

  - name: "post"
    label: "Post"
    folder: "TheVault/entries"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "index", name: "index", widget: "number" }
      - { label: "display_index", name: "display_index", widget: "string" }
      - { label: "published", name: "published", widget: "boolean", default: true}
      - { label: "date", name: "date", widget: "datetime" }
      - { label: "Post title", name: "title", widget: "string" }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Post content', name: 'body', widget: 'markdown' }
